In [6]:
from nhlpy import NHLClient
from src.utils import dataloading as dl

%load_ext autoreload
%autoreload 2

The autoreload extension is already loaded. To reload it, use:
  %reload_ext autoreload

In [2]:
client = NHLClient(
    debug=True,           # Enable debug logging
    timeout=30,           # Request timeout in seconds
    ssl_verify=True,      # SSL certificate verification
    follow_redirects=True # Follow HTTP redirects
)

teams = client.teams.teams()
standings = client.standings.league_standings()
games = client.schedule.daily_schedule()

nhlpy.http_client - DEBUG - GET: https://api-web.nhle.com/v1/standings/now
nhlpy.http_client - DEBUG - GET: https://api.nhle.com/stats/rest/en/franchise
nhlpy.http_client - DEBUG - GET: https://api-web.nhle.com/v1/standings/now
nhlpy.http_client - DEBUG - GET: https://api-web.nhle.com/v1/schedule/2026-05-22

In [1]:
import pandas as pd
from pathlib import Path
from nhlpy import NHLClient

df = pd.read_csv(Path('data/raw/games.csv'))

C:\Users\david\AppData\Local\Temp\ipykernel_38620\4122911985.py:5: DtypeWarning: Columns (0: venue_fi, 1: venue_cs, 2: venue_sk, 3: venue_sv, 4: venue_de, 5: awayTeam_radioLink, 6: homeTeam_radioLink) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(Path('data/raw/games.csv'))

In [2]:
df.loc[(df.homeTeam_abbrev == 'PHI') & (df.season == 20252026),:]

,id,season,gameType,startTimeUTC,venue_default,awayTeam_id,awayTeam_commonName_default,awayTeam_placeName_default,awayTeam_placeNameWithPreposition_default,awayTeam_placeNameWithPreposition_fr,...,homeTeam_placeName_fi,homeTeam_placeName_sk,homeTeam_placeName_sv,homeTeam_placeNameWithPreposition_cs,homeTeam_placeNameWithPreposition_es,homeTeam_placeNameWithPreposition_fi,homeTeam_placeNameWithPreposition_sk,homeTeam_placeNameWithPreposition_sv,awayTeam_radioLink,homeTeam_radioLink
25048,2025010047,20252026,1,2025-09-27 21:00:00+00:00,Xfinity Mobile Arena,6,Bruins,Boston,Boston,de Boston,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
25084,2025010083,20252026,1,2025-10-02 23:00:00+00:00,Xfinity Mobile Arena,2,Islanders,New York,New York,de New York,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
25092,2025010094,20252026,1,2025-10-04 16:30:00+00:00,Xfinity Mobile Arena,1,Devils,New Jersey,New Jersey,du New Jersey,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
25146,2025020044,20252026,2,2025-10-13 23:00:00+00:00,Xfinity Mobile Arena,13,Panthers,Florida,Florida,de la Floride,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
25167,2025020066,20252026,2,2025-10-16 23:00:00+00:00,Xfinity Mobile Arena,52,Jets,Winnipeg,Winnipeg,de Winnipeg,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
25183,2025020081,20252026,2,2025-10-18 23:00:00+00:00,Xfinity Mobile Arena,30,Wild,Minnesota,Minnesota,du Minnesota,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
25196,2025020094,20252026,2,2025-10-20 23:00:00+00:00,Xfinity Mobile Arena,55,Kraken,Seattle,Seattle,de Seattle,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
25229,2025020127,20252026,2,2025-10-25 16:30:00+00:00,Xfinity Mobile Arena,2,Islanders,New York,New York,de New York,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
25252,2025020150,20252026,2,2025-10-28 22:00:00+00:00,Xfinity Mobile Arena,5,Penguins,Pittsburgh,Pittsburgh,de Pittsburgh,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
25272,2025020170,20252026,2,2025-10-30 23:00:00+00:00,Xfinity Mobile Arena,18,Predators,Nashville,Nashville,de Nashville,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
25290,2025020188,20252026,2,2025-11-01 23:00:00+00:00,Xfinity Mobile Arena,10,Maple Leafs,Toronto,Toronto,de Toronto,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
25298,2025020196,20252026,2,2025-11-03 00:00:00+00:00,Xfinity Mobile Arena,20,Flames,Calgary,Calgary,de Calgary,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
25334,2025020232,20252026,2,2025-11-08 18:00:00+00:00,Xfinity Mobile Arena,9,Senators,Ottawa,Ottawa,d'Ottawa,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
25368,2025020266,20252026,2,2025-11-13 00:30:00+00:00,Xfinity Mobile Arena,22,Oilers,Edmonton,Edmonton,d'Edmonton,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
25425,2025020324,20252026,2,2025-11-21 00:00:00+00:00,Xfinity Mobile Arena,19,Blues,St. Louis,St. Louis,de St. Louis,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
25441,2025020339,20252026,2,2025-11-23 00:00:00+00:00,Xfinity Mobile Arena,1,Devils,New Jersey,New Jersey,du New Jersey,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
25509,2025020407,20252026,2,2025-12-02 00:00:00+00:00,Xfinity Mobile Arena,5,Penguins,Pittsburgh,Pittsburgh,de Pittsburgh,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
25525,2025020423,20252026,2,2025-12-04 00:30:00+00:00,Xfinity Mobile Arena,7,Sabres,Buffalo,Buffalo,de Buffalo,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
25555,2025020453,20252026,2,2025-12-07 18:00:00+00:00,Xfinity Mobile Arena,21,Avalanche,Colorado,Colorado,du Colorado,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
25571,2025020469,20252026,2,2025-12-10 00:00:00+00:00,Xfinity Mobile Arena,28,Sharks,San Jose,San Jose,de San Jose,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
25585,2025020483,20252026,2,2025-12-12 00:00:00+00:00,Xfinity Mobile Arena,54,Golden Knights,Vegas,Vegas,de Vegas,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
25603,2025020501,20252026,2,2025-12-14 00:00:00+00:00,Xfinity Mobile Arena,12,Hurricanes,Carolina,Carolina,de la Caroline,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
25674,2025020572,20252026,2,2025-12-23 00:30:00+00:00,Xfinity Mobile Arena,23,Canucks,Vancouver,Vancouver,de Vancouver,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
25771,2025020670,20252026,2,2026-01-07 00:00:00+00:00,Xfinity Mobile Arena,24,Ducks,Anaheim,Anaheim,d'Anaheim,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
25788,2025020686,20252026,2,2026-01-09 00:00:00+00:00,Xfinity Mobile Arena,10,Maple Leafs,Toronto,Toronto,de Toronto,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
25807,2025020705,20252026,2,2026-01-11 00:00:00+00:00,Xfinity Mobile Arena,14,Lightning,Tampa Bay,Tampa Bay,de Tampa Bay,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
25821,2025020719,20252026,2,2026-01-13 00:00:00+00:00,Xfinity Mobile Arena,14,Lightning,Tampa Bay,Tampa Bay,de Tampa Bay,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
25857,2025020755,20252026,2,2026-01-17 18:00:00+00:00,Xfinity Mobile Arena,3,Rangers,New York,New York,de New York,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
25929,2025020827,20252026,2,2026-01-27 00:00:00+00:00,Xfinity Mobile Arena,2,Islanders,New York,New York,de New York,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
25960,2025020859,20252026,2,2026-01-31 17:30:00+00:00,Xfinity Mobile Arena,26,Kings,Los Angeles,Los Angeles,de Los Angeles,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
25988,2025020889,20252026,2,2026-02-04 00:00:00+00:00,Xfinity Mobile Arena,15,Capitals,Washington,Washington,de Washington,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
26007,2025020907,20252026,2,2026-02-06 00:00:00+00:00,Xfinity Mobile Arena,9,Senators,Ottawa,Ottawa,d'Ottawa,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
26066,2025020935,20252026,2,2026-02-28 20:00:00+00:00,Xfinity Mobile Arena,6,Bruins,Boston,Boston,de Boston,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
26107,2025020976,20252026,2,2026-03-06 00:00:00+00:00,Xfinity Mobile Arena,68,Mammoth,Utah,Utah,de l'Utah,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
26140,2025021008,20252026,2,2026-03-09 23:00:00+00:00,Xfinity Mobile Arena,3,Rangers,New York,New York,de New York,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
26158,2025021026,20252026,2,2026-03-11 23:30:00+00:00,Xfinity Mobile Arena,15,Capitals,Washington,Washington,de Washington,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
26184,2025021052,20252026,2,2026-03-14 23:30:00+00:00,Xfinity Mobile Arena,29,Blue Jackets,Columbus,Columbus,de Columbus,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
26257,2025021125,20252026,2,2026-03-24 23:00:00+00:00,Xfinity Mobile Arena,29,Blue Jackets,Columbus,Columbus,de Columbus,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
26274,2025021142,20252026,2,2026-03-26 23:00:00+00:00,Xfinity Mobile Arena,16,Blackhawks,Chicago,Chicago,de Chicago,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
26304,2025021172,20252026,2,2026-03-29 23:00:00+00:00,Xfinity Mobile Arena,25,Stars,Dallas,Dallas,de Dallas,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
26327,2025021196,20252026,2,2026-04-02 23:00:00+00:00,Xfinity Mobile Arena,17,Red Wings,Detroit,Detroit,de Detroit,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
26356,2025021224,20252026,2,2026-04-05 19:30:00+00:00,Xfinity Mobile Arena,6,Bruins,Boston,Boston,de Boston,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
26416,2025021284,20252026,2,2026-04-13 23:00:00+00:00,Xfinity Mobile Arena,12,Hurricanes,Carolina,Carolina,de la Caroline,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
26426,2025021294,20252026,2,2026-04-14 23:00:00+00:00,Xfinity Mobile Arena,8,Canadiens,Montréal,Montréal,de Montréal,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
26460,2025030143,20252026,3,2026-04-22 23:00:00+00:00,Xfinity Mobile Arena,5,Penguins,Pittsburgh,Pittsburgh,de Pittsburgh,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
26471,2025030144,20252026,3,2026-04-26 00:00:00+00:00,Xfinity Mobile Arena,5,Penguins,Pittsburgh,Pittsburgh,de Pittsburgh,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
26482,2025030146,20252026,3,2026-04-29 23:30:00+00:00,Xfinity Mobile Arena,5,Penguins,Pittsburgh,Pittsburgh,de Pittsburgh,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
26497,2025030223,20252026,3,2026-05-08 00:00:00+00:00,Xfinity Mobile Arena,12,Hurricanes,Carolina,Carolina,de la Caroline,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
26500,2025030224,20252026,3,2026-05-09 22:00:00+00:00,Xfinity Mobile Arena,12,Hurricanes,Carolina,Carolina,de la Caroline,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [3]:
client = NHLClient(
    debug=True,           # Enable debug logging
    timeout=30,           # Request timeout in seconds
    ssl_verify=True,      # SSL certificate verification
    follow_redirects=True # Follow HTTP redirects
)

pd.json_normalize(client.game_center.play_by_play(game_id='2025020094')['plays'], sep='_')

nhlpy.http_client - DEBUG - GET: https://api-web.nhle.com/v1/gamecenter/2025020094/play-by-play

,eventId,timeInPeriod,timeRemaining,situationCode,homeTeamDefendingSide,typeCode,typeDescKey,sortOrder,periodDescriptor_number,periodDescriptor_periodType,...,details_assist2PlayerTotal,details_awayScore,details_homeScore,details_highlightClipSharingUrl,details_highlightClipSharingUrlFr,details_highlightClip,details_highlightClipFr,details_discreteClip,details_discreteClipFr,details_servedByPlayerId
0,52,00:00,20:00,1551,right,520,period-start,8,1,REG,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,51,00:00,20:00,1551,right,502,faceoff,11,1,REG,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,8,00:29,19:31,1551,right,516,stoppage,12,1,REG,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,55,00:29,19:31,1551,right,502,faceoff,15,1,REG,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,65,00:53,19:07,1551,right,503,hit,16,1,REG,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
313,434,19:09,00:51,1551,right,516,stoppage,821,3,REG,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
314,1145,19:09,00:51,1551,right,502,faceoff,824,3,REG,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
315,1149,19:21,00:39,1551,right,506,shot-on-goal,825,3,REG,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
316,435,20:00,00:00,1551,right,521,period-end,827,3,REG,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
317,440,20:00,00:00,1551,right,524,game-end,832,3,REG,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN